name: Setup webhook for self hosted runner

on:
  workflow_dispatch:
jobs:
  setup:
    runs-on: ubuntu-latest
    name: "Setup the webhook"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: "Execute script of webhook setup"
        uses: actions/github-script@v6
        env:
          WEBHOOK_SELF_HOSTED_RUNNER: '${{ secrets.WEBHOOK_SELF_HOSTED_RUNNER }}'
          WEBHOOK_HANDLE_JOB_QUEUED_AUTH_FUNC: '${{ secrets.WEBHOOK_HANDLE_JOB_QUEUED_AUTH_FUNC }}'
          WEBHOOK_HANDLE_JOB_QUEUED_URL: '${{ vars.WEBHOOK_HANDLE_JOB_QUEUED_URL }}'
        with:
          github-token: ${{ secrets.WEBHOOK_PAT }}
          script: |
            const { default: script } = await import('${{ github.workspace }}/src/setup-webhook.js')
            await script({github, context, core}, 'rmajid-aca-app')
      
